import os
import time
from datetime import datetime
from src.utils.logger import setup_logger
from src.utils.config import config

logger = setup_logger("rule_generator")

class SnortRuleGenerator:

    def __init__(self):
        self.rules_path = config.get(
            "snort", "rules_path",
            default="snort/rules/local.rules"
        )
        self.generated_rules = []
        self.blocked_ips = set()
        self.sid_counter = 2000000

    def _get_next_sid(self):
        self.sid_counter += 1
        return self.sid_counter

    def generate_ip_block_rule(self, src_ip: str, severity: str, attack_type: str) -> str:
        if src_ip in self.blocked_ips:
            return None
        sid = self._get_next_sid()
        rule = (
            f'alert ip {src_ip} any -> $HOME_NET any '
            f'(msg:"SENTINEL-ML {attack_type} from {src_ip}"; '
            f'priority:1; sid:{sid}; rev:1;)'
        )
        self.blocked_ips.add(src_ip)
        return rule

    def generate_port_rule(self, dst_port: int, protocol: str, attack_type: str) -> str:
        sid = self._get_next_sid()
        proto = protocol.lower() if protocol else "tcp"
        rule = (
            f'alert {proto} any any -> $HOME_NET {dst_port} '
            f'(msg:"SENTINEL-ML {attack_type} on port {dst_port}"; '
            f'threshold:type both,track by_src,count 50,seconds 10; '
            f'priority:2; sid:{sid}; rev:1;)'
        )
        return rule

    def generate_rule_from_alert(self, alert: dict) -> str:
        severity = alert.get("severity", "")
        attack_type = alert.get("attack_type", "Unknown")
        src_ip = alert.get("src_ip", "")
        dst_port = alert.get("dst_port", 0)
        protocol = alert.get("protocol", "tcp")

        if severity == "CRITICAL" and src_ip:
            return self.generate_ip_block_rule(src_ip, severity, attack_type)
        elif severity in ["HIGH", "MEDIUM"] and dst_port:
            return self.generate_port_rule(dst_port, protocol, attack_type)
        return None

    def save_rule(self, rule: str):
        try:
            os.makedirs(os.path.dirname(self.rules_path), exist_ok=True)
            with open(self.rules_path, "a") as f:
                f.write(f"\n# Auto-generated by ML — {datetime.now().isoformat()}\n")
                f.write(rule + "\n")
            self.generated_rules.append(rule)
            logger.info(f"New Snort rule generated: {rule[:60]}...")
            return True
        except Exception as e:
            logger.error(f"Error saving rule: {e}")
            return False

    def process_alert(self, alert: dict):
        if not alert.get("is_threat"):
            return None
        rule = self.generate_rule_from_alert(alert)
        if rule:
            self.save_rule(rule)
            return rule
        return None

    def get_generated_count(self) -> int:
        return len(self.generated_rules)

    def get_recent_rules(self, limit: int = 10) -> list:
        return self.generated_rules[-limit:]
